---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - trino.trino.io
  resources:
  - trinoclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - trino.trino.io
  resources:
  - trinoclusters/finalizers
  verbs:
  - update
- apiGroups:
  - trino.trino.io
  resources:
  - trinoclusters/status
  verbs:
  - get
  - patch
  - update
